export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  COURSES: '/courses',
  COURSE_CATEGORIES: '/courses/categories',
  INSTRUCTORS: '/instructors',
  STUDENTS: '/students',
  ANALYTICS: '/analytics',
  SUBSCRIPTION: '/subscription',
  FORGOT_PASSWORD: '/forgot-password',
  SETTINGS: '/settings',
  BRANDING: '/settings/branding',
  CONTACT_ADMIN: '/contact-admin',
} as const;
